# Advanced Querying Mongo

Importing libraries and setting up connection

In [ ]:
# from pymongo import MongoClient
# client = MongoClient("")

In [2]:
!pip3 install pymongo

Collecting pymongo
  Downloading pymongo-3.11.0-cp38-cp38-macosx_10_9_x86_64.whl (379 kB)
     |████████████████████████████████| 379 kB 3.9 MB/s eta 0:00:01
Installing collected packages: pymongo
Successfully installed pymongo-3.11.0

In [16]:
from pymongo import MongoClient
import pandas as pd

In [17]:
conn = MongoClient('localhost:27017')

In [18]:
# choose database to work with
db = conn.get_database('ironhack')

In [63]:
collection = db.get_collection('companies')

In [64]:
dataset = collection.find()

In [65]:
type(dataset)

pymongo.cursor.Cursor

In [66]:
df = pd.DataFrame(dataset)

In [67]:
df.head()

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,offices,milestones,video_embeds,screenshots,external_links,partners,deadpooled_month,deadpooled_day,deadpooled_url,ipo
0,52cdef7c4bab8bd675297d8a,Wetpaint,abc2,http://www.crunchbase.com/company/wetpaint,http://wetpaint-inc.com,http://digitalquarters.net/,http://digitalquarters.net/feed/,BachelrWetpaint,web,47.0,...,"[{'description': '', 'address1': '710 - 2nd Av...","[{'id': 5869, 'description': 'Wetpaint named i...",[],"[{'available_sizes': [[[150, 86], 'assets/imag...",[{'external_url': 'http://www.geekwire.com/201...,[],NaN,NaN,NaN,NaN
1,52cdef7c4bab8bd675297d8b,AdventNet,abc3,http://www.crunchbase.com/company/adventnet,http://adventnet.com,,,manageengine,enterprise,600.0,...,"[{'description': 'Headquarters', 'address1': '...",[],[],"[{'available_sizes': [[[150, 94], 'assets/imag...",[],[],NaN,NaN,NaN,NaN
2,52cdef7c4bab8bd675297d8c,Zoho,abc4,http://www.crunchbase.com/company/zoho,http://zoho.com,http://blogs.zoho.com/,http://blogs.zoho.com/feed,zoho,software,1600.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 388, 'description': 'Zoho Reaches 2 Mi...","[{'embed_code': '<object width=""430"" height=""2...",[],[{'external_url': 'http://www.online-tech-tips...,[],NaN,NaN,NaN,NaN
3,52cdef7c4bab8bd675297d8d,Digg,digg,http://www.crunchbase.com/company/digg,http://www.digg.com,http://blog.digg.com/,http://blog.digg.com/?feed=rss2,digg,news,60.0,...,"[{'description': None, 'address1': '135 Missis...","[{'id': 9588, 'description': 'Another Digg Exe...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[117, 150], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[],NaN,NaN,None,None
4,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,...,"[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[],NaN,NaN,,"{'valuation_amount': 104000000000, 'valuation_..."

### 1. All the companies whose name match 'Babelgum'. Retrieve only their `name` field.

In [68]:
# Your Code
collection.find({'name': 'Babelgum'}, {'name': 1})

In [69]:
list(_)

[{'_id': ObjectId('52cdef7c4bab8bd675297da0'), 'name': 'Babelgum'}]

### 2. All the companies that have more than 5000 employees. Limit the search to 20 companies and sort them by **number of employees**.

In [70]:
# Your Code
c = collection

In [73]:
c.find_one({"number_of_employees": {"$gt": 5000}})

{'_id': ObjectId('52cdef7c4bab8bd675297d8e'),
 'name': 'Facebook',
 'permalink': 'facebook',
 'crunchbase_url': 'http://www.crunchbase.com/company/facebook',
 'homepage_url': 'http://facebook.com',
 'blog_url': 'http://blog.facebook.com',
 'blog_feed_url': 'http://blog.facebook.com/atom.php',
 'twitter_username': 'facebook',
 'category_code': 'social',
 'number_of_employees': 5299,
 'founded_year': 2004,
 'founded_month': 2,
 'founded_day': 1,
 'deadpooled_year': None,
 'deadpooled_month': None,
 'deadpooled_day': None,
 'deadpooled_url': '',
 'tag_list': 'facebook, college, students, profiles, network, online-communities, social-networking',
 'alias_list': '',
 'email_address': '',
 'phone_number': '',
 'description': 'Social network',
 'created_at': 'Fri May 25 21:22:15 UTC 2007',
 'updated_at': 'Thu Nov 21 19:40:55 UTC 2013',
 'overview': '<p>Facebook is the world&#8217;s largest social network, with over <a href="http://techcrunch.com/2013/07/24/facebook-growth-2/" title="1.15 billion monthly active users">1.15 billion monthly active users</a>.</p>\n\n<p>Facebook was founded by <a href="http://www.crunchbase.com/person/mark-zuckerberg" title="Mark Zuckerberg">Mark Zuckerberg</a> in February 2004, initially as an exclusive network for Harvard students. It was a huge hit: in 2 weeks, half of the schools in the Boston area began demanding a Facebook network. Zuckerberg immediately recruited his friends <a href="http://www.crunchbase.com/person/dustin-moskovitz" title="Dustin Moskovitz">Dustin Moskovitz</a>, <a href="/person/chris-hughes" title="Chris Hughes" rel="nofollow">Chris Hughes</a>, and <a href="/person/eduardo-saverin" title="Eduardo Saverin" rel="nofollow">Eduardo Saverin</a> to help build Facebook, and within four months, Facebook added 30 more college networks. </p>\n\n<p>The original idea for the term Facebook came from Zuckerberg&#8217;s high school (Phillips Exeter Academy). The Exeter Face Book was passed around to every student as a way for students to get to know their classmates for the following year. It was a physical paper book until Zuckerberg brought it to the internet.</p>\n\n<p>With this success, Zuckerberg, Moskowitz and Hughes moved out to <a href="/maps/city/Palo%2520Alto" title="Palo Alto" rel="nofollow">Palo Alto</a> for the summer and rented a sublet. A few weeks later, Zuckerberg ran into the former cofounder of <a href="/company/napster" title="Napster" rel="nofollow">Napster</a>, <a href="/person/sean-parker" title="Sean Parker" rel="nofollow">Sean Parker</a>. Parker soon moved in to Zuckerberg&#8217;s apartment and they began working together.  Parker provided the introduction to their first investor, <a href="/person/peter-thiel" title="Peter Thiel" rel="nofollow">Peter Thiel</a>, cofounder of <a href="/company/paypal" title="PayPal" rel="nofollow">PayPal</a> and managing partner of <a href="http://www.crunchbase.com/financial-organization/founders-fund" title="The Founders Fund">The Founders Fund</a>. Thiel invested $500,000 into Facebook. </p>\n\n<p>With millions more users, <a href="/company/friendster" title="Friendster" rel="nofollow">Friendster</a> <a href="http://www.techcrunch.com/2006/12/12/yahoos-project-fraternity-docs-leaked/" title="attempted">attempted</a> to acquire the company for $10 million in mid 2004. Facebook turned down the offer and subsequently received $12.7 million in funding from <a href="http://www.crunchbase.com/financial-organization/accel-partners" title="Accel Partners">Accel Partners</a>, at a valuation of <a href="http://www.techcrunch.com/2005/09/07/85-of-college-students-use-facebook/" title="around $100 million">around $100 million</a>. Facebook continued to grow, opening up to high school students in September 2005 and adding an immensely popular photo sharing feature the next month. The next spring, Facebook received $25 million in funding from <a href="http://www.crunchbase.com/financial-organization/greylock" title="Greylock Partners">Greylock Partners</a> and <a href="http://www.crunchbase.com/financial-organization/meritech-capital-partners" title="Meritech Capital">Meritech Capital</a>, as well as previous investors Accel Partners and Peter Thiel. The pre-money valuation for this deal was about $525 million. Facebook subsequently <a href="http://www.techcrunch.com/2006/04/26/facebook-goes-beyond-college-high-school-markets/" title="opened">opened</a> up to work networks, eventually amassing over 20,000 work networks. Finally in September 2006, Facebook <a href="http://www.techcrunch.com/2006/09/26/facebook-just-launched-open-registrations/" title="opened">opened</a> to anyone with an email address. </p>\n\n<p>In the summer of 2006, <a href="/company/yahoo" title="Yahoo" rel="nofollow">Yahoo</a> <a href="http://www.techcrunch.com/2006/09/21/facebook-and-yahoo-in-acquisition-talks-for-1-billion/" title="attempted to acquire">attempted to acquire</a> the company for $1 billion dollars. <a href="http://www.wired.com/techbiz/startups/news/2007/09/ff_facebook" title="Reports" rel="nofollow">Reports</a> actually indicated that Zuckerberg made a verbal agreement to sell Facebook to Yahoo. A few days later when Yahoo&#8217;s stock price took a dive, the offer was lowered to $800 million and Zuckerberg walked away from the deal.  Yahoo later <a href="http://www.techcrunch.com/2006/12/12/yahoos-project-fraternity-docs-leaked/" title="offered">offered</a> $1 billion again, this time Zuckerberg turned Yahoo down and earned instant notoriety as the &#8220;kid&#8221; who turned down a billion. This was not the first time Zuckerberg turned down an acquisition offer; <a href="/company/viacom" title="Viacom" rel="nofollow">Viacom</a> had previously <a href="http://www.techcrunch.com/2006/03/28/facebook-is-doing-the-skype-dance/" title="unsuccessfully">unsuccessfully</a> attempted to acquire the company for $750 million in March 2006. </p>\n\n<p>Not long after, in October 2007, <a href="http://www.techcrunch.com/2007/10/24/facebook-takes-the-microsoft-money-and-runs/" title="Microsoft invested">Microsoft invested</a> $240 million into Facebook for 1.6 percent of the company in. This meant a valuation of over $15 billion, making Facebook the <a href="http://www.techcrunch.com/2007/10/25/perspective-facebook-is-now-5th-most-valuable-us-internet-company/" title="5th most valuable US Internet company">5th most valuable US Internet company</a>, yet with only $150 million in annual revenue. Many explained Microsoft&#8217;s decision as being solely driven by the desire to outbid Google.</p>\n\n<p>Facebook continued to receive funding, most notably in January 2011 receiving a <a href="http://techcrunch.com/2011/01/21/facebook-raises-1-5-billion-at-50-billion-valuation/" title="$1.5 billion round">$1.5 billion round</a>, valuing the company at $50 billion. A year later, in February 2012, Facebook <a href="http://techcrunch.com/2012/02/01/facebook-files-for-5-billion-ipo/" title="announced">announced</a> that it was filing for its long-anticipated initial public offering. The company went public on May 18, 2012, opening on the NASDAQ with shares trading at <a href="http://techcrunch.com/2012/05/18/facebook-share-open-10-5-higher-at-42/" title="$42.05">$42.05</a>.</p>\n\n<p>One sour note for Facebook has been the <a href="http://www.techcrunch.com/2007/07/16/the-ghost-of-zuckerbergs-past-may-haunt-facebook-ipo/" title="controversy">controversy</a> with social network ConnectU. The founders of ConnectU, former classmates of Mark Zuckerberg at Harvard, allege that Zuckerberg stole their original source code for Facebook. The ordeal has <a href="http://www.techcrunch.com/2007/10/10/facebook-vs-connectu-facebook-makes-untrue-assertions-claims-connectu/" title="gone to court">gone to court</a>, and has now been <a href="http://techcrunch.com/2011/06/22/after-seven-years-the-winklevosses-give-up-on-battle-with-facebook/" title="resolved">resolved</a>. </p>\n\n<p>Notwithstanding this lingering controversy, Facebook&#8217;s growth has been staggering. Facebook announced <a href="http://techcrunch.com/2012/02/01/facebooks-s-1-845-million-users-every-month-more-than-half-daily-and-nearly-half-mobile/" title="astonishing numbers">astonishing numbers</a> in February 2012 upon filing for its IPO. As of July 2013, over <a href="http://techcrunch.com/2013/07/24/facebook-growth-2/" title="1.15 billion">1.15 billion</a> users log into Facebook every month, and 669 million users log in daily. Mobile users now make up half of Facebook&#8217;s user base, with 819 million monthly actives. Facebook has also announced that by the end of 2011 there had been 100 billion friend connections, and in recent months users had been registering 2.7 billion Likes and Comments per day. Facebook is one of the <a href="http://techcrunch.com/2010/12/29/hitwise-facebook-overtakes-google-to-become-most-visited-website-in-2010/" title="most trafficked sites">most trafficked sites</a> in the US, and its international growth has been impressive. Additionally, Facebook is the top photo sharing site with 250 million photos uploaded per day.</p>\n\n<p>Facebook users&#8217; <a href="http://www.techcrunch.com/2007/11/13/i-just-cant-be-a-college-student-without-facebook/" title="passion">passion</a>—or <a href="http://www.techcrunch.com/2007/03/09/career-advice-dont-choose-facebook-over-your-job/" title="addiction">addiction</a>—to the site is unparalleled: more than half use the product every single day and users spend an average of 19 minutes a day on Facebook. The site&#8217;s popularity has garnered it pop culture fame, so much so that in 2010 a feature film entitled <em>The Social Network</em> was released which chronicled Facebook&#8217;s inception.</p>\n\n<p>In its 2012 <a href="http://techcrunch.com/2012/02/01/facebook-files-for-5-billion-ipo/" title="IPO filing">IPO filing</a>, Facebook announced that it intends to grow in the near future by expanding its global user base, increasing engagement by developing new social tools, improving the mobile experience, and creating more value for advertisers and users.</p>',
 'image': {'available_sizes': [[[150, 61],
    'assets/images/resized/0000/4561/4561v1-max-150x150.png'],
   [[245, 100], 'assets/images/resized/0000/4561/4561v1-max-250x250.png'],
   [[245, 100], 'assets/images/resized/0000/4561/4561v1-max-450x450.png']],
  'attribution': None},
 'products': [{'name': 'Facebook Platform', 'permalink': 'facebook-platform'},
  {'name': 'Facebook News Feed', 'permalink': 'facebook-news-feed'},
  {'name': 'Facebook Chat', 'permalink': 'facebook-chat'},
  {'name': 'Facebook Connect', 'permalink': 'facebook-connect'},
  {'name': 'Facebook Mobile', 'permalink': 'facebook-iphone-app'},
  {'name': 'Facebook', 'permalink': 'facebook-zero'},
  {'name': 'Facebook Lite', 'permalink': 'facebook-lite'},
  {'name': 'Facebook Places', 'permalink': 'facebook-places'}],
 'relationships': [{'is_past': False,
   'title': 'Founder and CEO, Board Of Directors',
   'person': {'first_name': 'Mark',
    'last_name': 'Zuckerberg',
    'permalink': 'mark-zuckerberg'}},
  {'is_past': False,
   'title': 'CFO',
   'person': {'first_name': 'David',
    'last_name': 'Ebersman',
    'permalink': 'david-ebersman'}},
  {'is_past': False,
   'title': 'COO',
   'person': {'first_name': 'Sheryl',
    'last_name': 'Sandberg',
    'permalink': 'sheryl-sandberg'}},
  {'is_past': False,
   'title': 'Vice- President and General Counsel',
   'person': {'first_name': 'Colin',
    'last_name': 'Stretch',
    'permalink': 'colin-stretch'}},
  {'is_past': False,
   'title': 'VP of Engineering & Product',
   'person': {'first_name': 'Peter',
    'last_name': 'Deng',
    'permalink': 'peter-deng'}},
  {'is_past': False,
   'title': 'VP, Global Advertising Sales',
   'person': {'first_name': 'Carolyn',
    'last_name': 'Everson',
    'permalink': 'carolyn-everson'}},
  {'is_past': False,
   'title': 'Vice President Advertising and Global Operations',
   'person': {'first_name': 'David',
    'last_name': 'Fischer',
    'permalink': 'david-fischer-2'}},
  {'is_past': False,
   'title': 'VP, EMEA',
   'person': {'first_name': 'Joanna',
    'last_name': 'Shields',
    'permalink': 'joanna-shields'}},
  {'is_past': False,
   'title': 'VP, Advertising',
   'person': {'first_name': 'Andrew',
    'last_name': 'Bosworth',
    'permalink': 'andrew-bosworth'}},
  {'is_past': False,
   'title': 'VP Human Resources, Recruiting',
   'person': {'first_name': 'Lori',
    'last_name': 'Goler',
    'permalink': 'lori-goler'}},
  {'is_past': False,
   'title': 'VP of Engineering',
   'person': {'first_name': 'Jay',
    'last_name': 'Parikh',
    'permalink': 'jay-parikh'}},
  {'is_past': False,
   'title': 'VP Product',
   'person': {'first_name': 'Chris',
    'last_name': 'Cox',
    'permalink': 'chris-cox'}},
  {'is_past': False,
   'title': 'VP Engineering & Products',
   'person': {'first_name': 'Greg',
    'last_name': 'Badros',
    'permalink': 'greg-badros'}},
  {'is_past': False,
   'title': 'VP of Partnerships and Platform Marketing',
   'person': {'first_name': 'Dan',
    'last_name': 'Rose',
    'permalink': 'dan-rose'}},
  {'is_past': False,
   'title': 'Vice President, Engineering',
   'person': {'first_name': 'Mike',
    'last_name': 'Schroepfer',
    'permalink': 'mike-shroepfer'}},
  {'is_past': False,
   'title': 'VP of Global Communications, Marketing and Public Policy',
   'person': {'first_name': 'Elliot',
    'last_name': 'Schrage',
    'permalink': 'elliot-schrage'}},
  {'is_past': False,
   'title': 'Board of Directors/Investor',
   'person': {'first_name': 'Jim',
    'last_name': 'Breyer',
    'permalink': 'jim-breyer'}},
  {'is_past': False,
   'title': 'Board Director',
   'person': {'first_name': 'Marc',
    'last_name': 'Andreessen',
    'permalink': 'marc-andreessen'}},
  {'is_past': False,
   'title': 'Director of Monetization',
   'person': {'first_name': 'Tim',
    'last_name': 'Kendall',
    'permalink': 'tim-kendall'}},
  {'is_past': False,
   'title': 'Head of Security',
   'person': {'first_name': 'Max',
    'last_name': 'Kelly',
    'permalink': 'max-kelly'}},
  {'is_past': False,
   'title': 'Marketing Director',
   'person': {'first_name': 'Randi',
    'last_name': 'Zuckerberg',
    'permalink': 'randi-zuckerberg'}},
  {'is_past': False,
   'title': 'Director of Public Policy',
   'person': {'first_name': 'Timothy',
    'last_name': 'Sparapani',
    'permalink': 'timothy-sparapani'}},
  {'is_past': False,
   'title': 'Product Manager',
   'person': {'first_name': 'Gareth',
    'last_name': 'Davis',
    'permalink': 'gareth-davis'}},
  {'is_past': False,
   'title': 'Business Development Manager',
   'person': {'first_name': 'Justin',
    'last_name': 'Osofsky',
    'permalink': 'justin-osofsky'}},
  {'is_past': False,
   'title': 'Platform Product Marketing',
   'person': {'first_name': 'Kelly',
    'last_name': 'Hansen',
    'permalink': 'kelly-hansen'}},
  {'is_past': False,
   'title': 'Manager, Site Reliability Engineering',
   'person': {'first_name': 'Pedro',
    'last_name': 'Canahuati',
    'permalink': 'pedro-canahuati'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Michael',
    'last_name': 'Novati',
    'permalink': 'michael-novati'}},
  {'is_past': False,
   'title': 'Engineering Director',
   'person': {'first_name': 'Pedram',
    'last_name': 'Keyani',
    'permalink': 'pedram-keyani'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'bill',
    'last_name': 'fumerola',
    'permalink': 'bill-fumerola'}},
  {'is_past': False,
   'title': 'Engineer',
   'person': {'first_name': 'Lars',
    'last_name': 'Rasmussen',
    'permalink': 'lars-rasmussen'}},
  {'is_past': False,
   'title': 'Manager of Product Marketing, Facebook Credits',
   'person': {'first_name': 'Deborah',
    'last_name': 'Liu',
    'permalink': 'deborah-liu'}},
  {'is_past': False,
   'title': 'Head of platform partnerships',
   'person': {'first_name': 'Julien',
    'last_name': 'Codorniou',
    'permalink': 'julien-codorniou'}},
  {'is_past': False,
   'title': 'Corporate Development',
   'person': {'first_name': 'Amin',
    'last_name': 'Zoufonoun',
    'permalink': 'amin-zoufonoun'}},
  {'is_past': False,
   'title': 'Director, Product Management',
   'person': {'first_name': 'Tom',
    'last_name': 'Stocky',
    'permalink': 'tom-stocky'}},
  {'is_past': False,
   'title': 'Monetization Analytics',
   'person': {'first_name': 'Jimmy',
    'last_name': 'Zhu',
    'permalink': 'jimmy-zhu'}},
  {'is_past': False,
   'title': 'Product Manager',
   'person': {'first_name': 'Justin',
    'last_name': 'Shaffer',
    'permalink': 'justin-shaffer'}},
  {'is_past': False,
   'title': 'Strategic Partner Manager, Games',
   'person': {'first_name': 'Niranjan',
    'last_name': 'Nagar',
    'permalink': 'niranjan-nagar'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Lincoln',
    'last_name': 'Hochberg',
    'permalink': 'lincoln-hochberg'}},
  {'is_past': False,
   'title': '',
   'person': {'first_name': 'Adam',
    'last_name': 'Cheyer',
    'permalink': 'adam-cheyer'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Zac',
    'last_name': 'Morris',
    'permalink': 'zac-morris'}},
  {'is_past': False,
   'title': 'Photos Product Manger',
   'person': {'first_name': 'Emily',
    'last_name': 'Grewal',
    'permalink': 'emily-grewal'}},
  {'is_past': False,
   'title': 'Director of Engineering',
   'person': {'first_name': 'John',
    'last_name': 'Ciancutti',
    'permalink': 'john-ciancutti'}},
  {'is_past': False,
   'title': 'Product Manager',
   'person': {'first_name': 'Eitan',
    'last_name': 'Shay',
    'permalink': 'eitan-shay'}},
  {'is_past': False,
   'title': 'Communication Designer',
   'person': {'first_name': 'Skyler',
    'last_name': 'Vander Molen',
    'permalink': 'skyler-vander-molen'}},
  {'is_past': False,
   'title': 'Product Designer',
   'person': {'first_name': 'Tuhin',
    'last_name': 'Kumar',
    'permalink': 'tuhin-kumar'}},
  {'is_past': False,
   'title': '',
   'person': {'first_name': 'Sriram',
    'last_name': 'Krishnan',
    'permalink': 'sriram-krishnan'}},
  {'is_past': False,
   'title': 'Manager of Strategic Partnerships',
   'person': {'first_name': 'Ime',
    'last_name': 'Archibong',
    'permalink': 'ime-archibong'}},
  {'is_past': False,
   'title': 'Strategic Partner Development - Commerce',
   'person': {'first_name': 'Chris',
    'last_name': 'Maliwat',
    'permalink': 'chris-maliwat'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Barak',
    'last_name': 'Naveh',
    'permalink': 'barak-naveh'}},
  {'is_past': False,
   'title': 'International Growth',
   'person': {'first_name': 'Edward',
    'last_name': 'Baker',
    'permalink': 'edward-baker'}},
  {'is_past': False,
   'title': 'Troublemaker',
   'person': {'first_name': 'Seng Keat',
    'last_name': 'Teh',
    'permalink': 'seng-keat-teh'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Lucy',
    'last_name': 'Zhang',
    'permalink': 'lucy-zhang'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Jonathan',
    'last_name': 'Perlow',
    'permalink': 'jonathan-perlow'}},
  {'is_past': False,
   'title': 'Head of Analytics',
   'person': {'first_name': 'Ken',
    'last_name': 'Rudin',
    'permalink': 'ken-rudin'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Michael',
    'last_name': 'Landau',
    'permalink': 'michael-landau'}},
  {'is_past': False,
   'title': 'Product Manager',
   'person': {'first_name': 'Gil',
    'last_name': 'Hirsch',
    'permalink': 'gil-hirsch'}},
  {'is_past': False,
   'title': 'Software Engineer',
   'person': {'first_name': 'Florian',
    'last_name': 'Laplantif',

In [74]:
list(c.find({'number_of_employees': {'$gt': 5000}}, {'name': 1, 'number_of_employees': 1}).sort('number_of_employees', -1).limit(20))

[{'_id': ObjectId('52cdef7d4bab8bd67529941a'),
  'name': 'Siemens',
  'number_of_employees': 405000},
 {'_id': ObjectId('52cdef7c4bab8bd67529856a'),
  'name': 'IBM',
  'number_of_employees': 388000},
 {'_id': ObjectId('52cdef7d4bab8bd675299d33'),
  'name': 'Toyota',
  'number_of_employees': 320000},
 {'_id': ObjectId('52cdef7c4bab8bd675297e89'),
  'name': 'PayPal',
  'number_of_employees': 300000},
 {'_id': ObjectId('52cdef7e4bab8bd67529b0fe'),
  'name': 'Nippon Telegraph and Telephone Corporation',
  'number_of_employees': 227000},
 {'_id': ObjectId('52cdef7d4bab8bd675298aa4'),
  'name': 'Samsung Electronics',
  'number_of_employees': 221726},
 {'_id': ObjectId('52cdef7d4bab8bd675298b99'),
  'name': 'Accenture',
  'number_of_employees': 205000},
 {'_id': ObjectId('52cdef7e4bab8bd67529a657'),
  'name': 'Tata Consultancy Services',
  'number_of_employees': 200300},
 {'_id': ObjectId('52cdef7e4bab8bd67529aa51'),
  'name': 'Flextronics International',
  'number_of_employees': 200000},
 {'_id': ObjectId('52cdef7d4bab8bd675299156'),
  'name': 'Safeway',
  'number_of_employees': 186000},
 {'_id': ObjectId('52cdef7c4bab8bd675297e6f'),
  'name': 'Sony',
  'number_of_employees': 180500},
 {'_id': ObjectId('52cdef7c4bab8bd675298517'),
  'name': 'LG',
  'number_of_employees': 177000},
 {'_id': ObjectId('52cdef7d4bab8bd675299d31'),
  'name': 'Ford',
  'number_of_employees': 171000},
 {'_id': ObjectId('52cdef7d4bab8bd675298b28'),
  'name': 'Boeing',
  'number_of_employees': 160000},
 {'_id': ObjectId('52cdef7e4bab8bd67529bb5c'),
  'name': 'Digital Equipment Corporation',
  'number_of_employees': 140000},
 {'_id': ObjectId('52cdef7c4bab8bd675297fc2'),
  'name': 'Nokia',
  'number_of_employees': 125000},
 {'_id': ObjectId('52cdef7d4bab8bd675299bc3'),
  'name': 'MItsubishi Electric',
  'number_of_employees': 107000},
 {'_id': ObjectId('52cdef7d4bab8bd675299839'),
  'name': 'MItsubishi Electric',
  'number_of_employees': 107000},
 {'_id': ObjectId('52cdef7d4bab8bd675298d67'),
  'name': 'Bertelsmann',
  'number_of_employees': 100000},
 {'_id': ObjectId('52cdef7c4bab8bd6752987ad'),
  'name': 'Comcast',
  'number_of_employees': 100000}]

### 3. All the companies founded between 2000 and 2005, both years included. Retrieve only the `name` and `founded_year` fields.

In [76]:
pd.DataFrame(c.find({'founded_year': {"$in": [2000, 2001, 2002, 2004, 2005]}}, {'name': 1, 'founded_year': 1}))

                           _id                     name  founded_year
0     52cdef7c4bab8bd675297d8a                 Wetpaint          2005
1     52cdef7c4bab8bd675297d8c                     Zoho          2005
2     52cdef7c4bab8bd675297d8d                     Digg          2004
3     52cdef7c4bab8bd675297d8e                 Facebook          2004
4     52cdef7c4bab8bd675297d8f                Omnidrive          2005
...                        ...                      ...           ...
3153  52cdef7f4bab8bd67529c6e0  Celestial Semiconductor          2004
3154  52cdef7f4bab8bd67529c6ee           EnterSys Group          2000
3155  52cdef7f4bab8bd67529c6ef           Axon Solutions          2004
3156  52cdef7f4bab8bd67529c6f7               AfterLogic          2002
3157  52cdef7f4bab8bd67529c6fa                EnteGreat          2000

[3158 rows x 3 columns]

### 4. All the companies that had a Valuation Amount of more than 100.000.000 and have been founded before 2010. Retrieve only the `name` and `ipo` fields.

In [138]:
# Your Code
pd.DataFrame(c.find(
    {"$and": [
        {'ipo.valuation_amount': {'$gt': 100000000}},
        {'founded_year': {"$lt": 2010}}
    ]},
    {"name": 1, "ipo.valuation_amount": 1}
))

,_id,name,ipo
0,52cdef7c4bab8bd675297d8e,Facebook,{'valuation_amount': 104000000000}
1,52cdef7c4bab8bd675297d94,Twitter,{'valuation_amount': 18100000000}
2,52cdef7c4bab8bd675297de0,Yelp,{'valuation_amount': 1300000000}
3,52cdef7c4bab8bd675297e0c,LinkedIn,{'valuation_amount': 9310000000}
4,52cdef7c4bab8bd675297e7a,Amazon,{'valuation_amount': 100000000000}
5,52cdef7c4bab8bd675297e81,Brightcove,{'valuation_amount': 290000000}
6,52cdef7c4bab8bd675297ee5,KIT digital,{'valuation_amount': 235000000}
7,52cdef7c4bab8bd675297f15,Nielsen,{'valuation_amount': 1600000000}
8,52cdef7c4bab8bd675297f36,OpenTable,{'valuation_amount': 1050000000}
9,52cdef7c4bab8bd675297f42,ChannelAdvisor,{'valuation_amount': 287000000}
10,52cdef7c4bab8bd675297f95,Jive Software,{'valuation_amount': 1000000000}
11,52cdef7c4bab8bd67529800c,Zillow,{'valuation_amount': 2550000000}
12,52cdef7c4bab8bd67529805d,Wix,{'valuation_amount': 750000000}
13,52cdef7c4bab8bd675298112,Shutterfly,{'valuation_amount': 350000000}
14,52cdef7c4bab8bd6752981a7,TripAdvisor,{'valuation_amount': 3273770000}
15,52cdef7c4bab8bd67529823b,Salesforce,{'valuation_amount': 110000000}
16,52cdef7c4bab8bd6752982f6,HomeAway,{'valuation_amount': 3000000000}
17,52cdef7c4bab8bd6752984e3,QuinStreet,{'valuation_amount': 140000000}
18,52cdef7c4bab8bd675298527,Rackspace,{'valuation_amount': 5440000000}
19,52cdef7c4bab8bd67529859a,BMC Software,{'valuation_amount': 6000000000}
20,52cdef7c4bab8bd675298649,Higher One,{'valuation_amount': 1060000000}
21,52cdef7c4bab8bd67529865c,Infoblox,{'valuation_amount': 824000000}
22,52cdef7c4bab8bd675298674,Tencent,{'valuation_amount': 11000000000}
23,52cdef7c4bab8bd675298696,Marketo,{'valuation_amount': 465000000}
24,52cdef7c4bab8bd675298760,Baidu,{'valuation_amount': 4000000000}
25,52cdef7c4bab8bd6752987fe,Geeknet,{'valuation_amount': 134000000}
26,52cdef7d4bab8bd6752989a0,Opsware,{'valuation_amount': 450000000}
27,52cdef7d4bab8bd6752989f2,Telenav,{'valuation_amount': 337000000}
28,52cdef7d4bab8bd675298d0e,Rally Software,{'valuation_amount': 315000000}
29,52cdef7d4bab8bd675298d12,BrightSource Energy,{'valuation_amount': 1000000000}
30,52cdef7d4bab8bd675299103,Mixi,{'valuation_amount': 970000000}
31,52cdef7d4bab8bd6752992c1,QlikTech,{'valuation_amount': 1000000000}
32,52cdef7d4bab8bd67529984e,Chegg,{'valuation_amount': 1100000000}
33,52cdef7d4bab8bd675299bd8,Chegg,{'valuation_amount': 1100000000}
34,52cdef7d4bab8bd675299d5d,Groupon,{'valuation_amount': 12800000000}
35,52cdef7e4bab8bd67529a7db,SolarWinds,{'valuation_amount': 803000000}
36,52cdef7e4bab8bd67529a8b4,GREE,{'valuation_amount': 108960000000}
37,52cdef7e4bab8bd67529aae7,Tudou,{'valuation_amount': 174000000}
38,52cdef7e4bab8bd67529ad05,DemandTec,{'valuation_amount': 245000000}
39,52cdef7e4bab8bd67529b3bd,Cornerstone OnDemand,{'valuation_amount': 900000000}
40,52cdef7e4bab8bd67529b996,Western Digital,{'valuation_amount': 9430000000}
41,52cdef7e4bab8bd67529bb87,Millennial Media,{'valuation_amount': 973500000}

### 5. All the companies that have less than 1000 employees and have been founded before 2005. Order them by the number of employees and limit the search to 10 companies.

In [96]:
# Your Code
list(c.find(
    {"$and": [
        {'number_of_employees': {'$lt': 1000}},
        {'founded_year': {"$lt": 2005}}
    ]},
    {"name": 1, "number_of_employees": 1}
).sort('number_of_employees', -1).limit(10))

[{'_id': ObjectId('52cdef7d4bab8bd675298933'),
  'name': 'Infinera Corporation',
  'number_of_employees': 974},
 {'_id': ObjectId('52cdef7e4bab8bd67529ac95'),
  'name': 'NorthPoint Communications Group',
  'number_of_employees': 948},
 {'_id': ObjectId('52cdef7f4bab8bd67529be17'),
  'name': '888 Holdings',
  'number_of_employees': 931},
 {'_id': ObjectId('52cdef7c4bab8bd6752986a2'),
  'name': 'Forrester Research',
  'number_of_employees': 903},
 {'_id': ObjectId('52cdef7e4bab8bd67529b21b'),
  'name': 'Webmetrics',
  'number_of_employees': 900},
 {'_id': ObjectId('52cdef7e4bab8bd67529af6d'),
  'name': 'SonicWALL',
  'number_of_employees': 900},
 {'_id': ObjectId('52cdef7e4bab8bd67529b3bd'),
  'name': 'Cornerstone OnDemand',
  'number_of_employees': 881},
 {'_id': ObjectId('52cdef7c4bab8bd67529857e'),
  'name': 'Buongiorno',
  'number_of_employees': 800},
 {'_id': ObjectId('52cdef7c4bab8bd6752985c5'),
  'name': 'Cvent',
  'number_of_employees': 800},
 {'_id': ObjectId('52cdef7c4bab8bd675297efd'),
  'name': 'ZoomInfo',
  'number_of_employees': 800}]

### 6. All the companies that don't include the `partners` field.

In [108]:
# Your Code
pd.DataFrame(c.find({"partners": {'$exists': False}}))

Empty DataFrame
Columns: []
Index: []

### 7. All the companies that have a null type of value on the `category_code` field.

In [120]:
# Your Code - question changed to All the companies whose name contains the substring "hola".
pd.DataFrame(c.find({'name' : {'$regex' : ".*hola.*"}}))

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7e4bab8bd67529acc2,Ethan Nicholas,ethan-nicholas,http://www.crunchbase.com/company/ethan-nicholas,http://www.ethannicholas.com/iShoot,,,None,mobile,None,...,[],None,[],[],[],None,"[{'embed_code': '<object width=""425"" height=""3...","[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]
1,52cdef7e4bab8bd67529b44a,Scholastic Books,scholastic-books,http://www.crunchbase.com/company/scholastic-b...,None,None,None,None,None,None,...,[],None,[],[],[],None,[],[],[],[]
2,52cdef7e4bab8bd67529bce2,Mobile Media Scholar,mobile-media-scholar,http://www.crunchbase.com/company/mobile-media...,None,None,None,None,None,None,...,[],None,[],[],[],None,[],[],[],[]

### 8. All the companies that have at least 100 employees but less than 1000. Retrieve only the `name` and `number of employees` fields.

In [113]:
# Your Code
pd.DataFrame(c.find(
    {"$and": [
        {'number_of_employees': {'$gt': 100}},
        {'number_of_employees': {'$lt': 1000}}
    ]},
    {'name': 1, 'number_of_employees': 1}
))

                          _id                   name  number_of_employees
0    52cdef7c4bab8bd675297d8b              AdventNet                  600
1    52cdef7c4bab8bd675297da7                AddThis                  120
2    52cdef7c4bab8bd675297da8                  OpenX                  305
3    52cdef7c4bab8bd675297db5               LifeLock                  644
4    52cdef7c4bab8bd675297dbb                  Jajah                  110
..                        ...                    ...                  ...
748  52cdef7f4bab8bd67529c6ac   Inventa Technologies                  207
749  52cdef7f4bab8bd67529c6d1  UOL (Universo Online)                  500
750  52cdef7f4bab8bd67529c6e6      OfficialVirtualDJ                  102
751  52cdef7f4bab8bd67529c6f1          Willdan Group                  385
752  52cdef7f4bab8bd67529c6f3                   QSGI                  164

[753 rows x 3 columns]

### 9. Order all the companies by their IPO price in a descending order.

In [191]:
# Your Code - Question changed to: Give a dictionary similar to {"CocaCola": 1000, "Pepsi": 900} with the top 10 companies regarding IPO price.
pd.DataFrame(c.find({'ipo.valuation_amount': {'$exists' :True}}).sort ('ipo.valuation_amount',-1).limit(11))

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7e4bab8bd67529a8b4,GREE,gree,http://www.crunchbase.com/company/gree,http://www.gree-corp.com,,,gree_corp,games_video,700.0,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': 104000000, 'price_currency_c...","[{'description': 'Headquarters', 'address1': '...","[{'id': 1021, 'description': 'IPO', 'stoned_ye...","{'valuation_amount': 108960000000, 'valuation_...",[],"[{'available_sizes': [[[133, 150], 'assets/ima...",[],[]
1,52cdef7c4bab8bd675297d8e,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Headquarters', 'address1': '...","[{'id': 108, 'description': 'Facebook adds com...","{'valuation_amount': 104000000000, 'valuation_...",[],"[{'available_sizes': [[[150, 68], 'assets/imag...",[{'external_url': 'http://latimesblogs.latimes...,[]
2,52cdef7c4bab8bd675297e7a,Amazon,amazon,http://www.crunchbase.com/company/amazon,http://amazon.com,,,amazon,ecommerce,NaN,...,"[{'funding_round': {'round_code': 'seed', 'sou...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': '1200 12th ...","[{'id': 6931, 'description': 'How Many Kindle ...","{'valuation_amount': 100000000000, 'valuation_...","[{'embed_code': '<object width=""425"" height=""3...","[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297d94,Twitter,twitter,http://www.crunchbase.com/company/twitter,http://twitter.com,http://twitter.com/blog,http://feeds.feedburner.com/TwitterBlog,twitter,social,1300.0,...,[],None,"[{'price_amount': 15000000, 'price_currency_co...","[{'description': '', 'address1': '1355 Market ...","[{'id': 1, 'description': 'Survives iPhone 3G ...","{'valuation_amount': 18100000000, 'valuation_c...","[{'embed_code': '<iframe width=""430"" height=""2...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://sec.gov/cgi-bin/brow...,[]
4,52cdef7d4bab8bd675299d5d,Groupon,groupon,http://www.crunchbase.com/company/groupon,http://www.groupon.com,http://www.groupon.com/blog/,feed://feeds2.feedburner.com/grouponblog,groupon,web,10000.0,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '600 W. Chi...","[{'id': 4396, 'description': 'Groupon Makes A ...","{'valuation_amount': 12800000000, 'valuation_c...","[{'embed_code': '<script src=""http://www.buzzs...","[{'available_sizes': [[[150, 97], 'assets/imag...",[{'external_url': 'http://web20show.com/2009/1...,[]
5,52cdef7c4bab8bd675298674,Tencent,tencent,http://www.crunchbase.com/company/tencent,http://www.tencent.com,,,,web,NaN,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': 'Tencent Buil...","[{'id': 7786, 'description': 'Annual revenue (...","{'valuation_amount': 11000000000, 'valuation_c...",[],[],[{'external_url': 'http://mashpedia.com/Tencen...,"[{'partner_name': 'CTQuan', 'homepage_url': 'h..."
6,52cdef7e4bab8bd67529b996,Western Digital,western-digital,http://www.crunchbase.com/company/western-digital,http://www.wdc.com/en,,,WesternDigital,hardware,NaN,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': 685000000, 'price_currency_c...","[{'description': 'HQ', 'address1': '20511 Lake...","[{'id': 6497, 'description': 'WDÂ® COMPLETES A...","{'valuation_amount': 9430000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 133], 'assets/ima...",[{'external_url': 'http://www.facebook.com/Wes...,[]
7,52cdef7c4bab8bd675297e0c,LinkedIn,linkedin,http://www.crunchbase.com/company/linkedin,http://linkedin.com,http://blog.linkedin.com,,linkedin,social,4800.0,...,[],None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '2029 Stier...","[{'id': 10120, 'description': 'LinkedIn CEO Je...","{'valuation_amount': 9310000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 75], 'assets/imag...",[{'external_url': 'http://www.linkedin.com/in/...,[]
8,52cdef7c4bab8bd67529859a,BMC Software,bmc-software,http://www.crunchbase.com/company/bmc-software,http://www.bmc.com,http://www.bmc.com/devops,,bmcsoftware,software,NaN,...,[],None,"[{'price_amount': 800000000, 'price_currency_c...","[{'description': '', 'address1': '2101 City We...","[{'id': 12987, 'description': 'BMC Software Se...","{'valuation_amount': 6000000000, 'valuation_cu...",[],"[{'available_sizes': [[[150, 105], 'assets/ima...",[],[]
9,52cdef7c4bab8bd675298527,Rackspace,rackspace,http://www.crunchbase.com/company/rackspace,http://www.rackspace.com,http://www.rackspace.com/blog/index.php,http://www.rackspace.com/blog/?feed=rss2,Rackspace,software,NaN,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ', 'address1': '5000 Walze...","[{'id': 17986, 'description': 'Added Susan J. ...","{'valuation_amount': 5440000000, 'valuation_cu...","[{'embed_code': '<object width=""430"" height=""2...","[{'available_sizes': [[[150, 94], 'assets/imag...",[],[]
10,52cdef7c4bab8bd675298760,Baidu,baidu,http://www.crunchbase.com/company/baidu,http://www.baidu.com,,,baidu_,search,6000.0,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': None, 'address1': 'No. 58 Nor...","[{'id': 3434, 'description': 'Banners Broker M...","{'valuation_amount': 4000000000, 'valuation_cu...","[{'embed_code': '<object width=""425"" height=""3...","[{'available_sizes': [[[150, 74], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Baidu'...,"[{'partner_name': 'CTQuan', 'homepage_url': 'h..."

### 10. Retrieve the 10 companies with more employees, order by the `number of employees`

In [128]:
# Your Code
pd.DataFrame(c.find().sort('number_of_employees', -1).limit(11))

,_id,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,...,investments,acquisition,acquisitions,offices,milestones,ipo,video_embeds,screenshots,external_links,partners
0,52cdef7d4bab8bd67529941a,Siemens,siemens,http://www.crunchbase.com/company/siemens,http://www.siemens.com,,,Siemens,hardware,405000,...,[],None,"[{'price_amount': 418000000, 'price_currency_c...","[{'description': '', 'address1': 'Wittelsbache...","[{'id': 35852, 'description': 'Siemens Receive...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<iframe width=""420"" height=""3...","[{'available_sizes': [[[150, 92], 'assets/imag...",[],[]
1,52cdef7c4bab8bd67529856a,IBM,ibm,http://www.crunchbase.com/company/ibm,http://www.ibm.com,,,IBM,software,388000,...,"[{'funding_round': {'round_code': 'c', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'Corporate Headquarters', 'ad...","[{'id': 10471, 'description': 'IBM Completes A...","{'valuation_amount': None, 'valuation_currency...","[{'embed_code': '<embed src=""http://blip.tv/pl...","[{'available_sizes': [[[150, 93], 'assets/imag...","[{'external_url': 'http://mashpedia.com/IBM', ...",[]
2,52cdef7d4bab8bd675299d33,Toyota,toyota,http://www.crunchbase.com/company/toyota,http://www.toyota-global.com,,,Toyota,enterprise,320000,...,"[{'funding_round': {'round_code': 'a', 'source...",None,[],"[{'description': 'HQ', 'address1': 'Toyota Mot...",[],None,"[{'embed_code': '<iframe width=""430"" height=""3...","[{'available_sizes': [[[150, 84], 'assets/imag...",[],[]
3,52cdef7c4bab8bd675297e89,PayPal,paypal,http://www.crunchbase.com/company/paypal,http://www.paypal.com,,,paypal,finance,300000,...,"[{'funding_round': {'round_code': 'c', 'source...","{'price_amount': 1500000000, 'price_currency_c...","[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '2145 E Hamil...","[{'id': 11916, 'description': 'Reserve Bank Of...",None,[],"[{'available_sizes': [[[150, 120], 'assets/ima...",[{'external_url': 'http://www.sociableblog.com...,[]
4,52cdef7e4bab8bd67529b0fe,Nippon Telegraph and Telephone Corporation,nippon-telegraph-and-telephone-corporation,http://www.crunchbase.com/company/nippon-teleg...,http://www.ntt.co.jp/index_e.html,,,,None,227000,...,"[{'funding_round': {'round_code': 'e', 'source...",None,[],"[{'description': 'NTT', 'address1': '3-1, Otem...",[],None,[],"[{'available_sizes': [[[150, 42], 'assets/imag...",[],[]
5,52cdef7d4bab8bd675298aa4,Samsung Electronics,samsung-electronics,http://www.crunchbase.com/company/samsung-elec...,http://www.samsung.com/us,http://www.samsungvillage.com/,,samsungtweets,hardware,221726,...,"[{'funding_round': {'round_code': 'b', 'source...",None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'HQ - South Korea', 'address1...","[{'id': 11908, 'description': 'Samsung Ships 3...",None,"[{'embed_code': '<iframe src=""http://blip.tv/p...","[{'available_sizes': [[[94, 150], 'assets/imag...",[{'external_url': 'http://mashpedia.com/Samsun...,[]
6,52cdef7d4bab8bd675298b99,Accenture,accenture,http://www.crunchbase.com/company/accenture,http://www.accenture.com,http://www.accenture.com/Global/Accenture_Blogs/,http://feeds.accenture.com/Accenture_High_Perf...,accenture,consulting,205000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': '', 'address1': '1615 Murray ...","[{'id': 1824, 'description': 'Nokia and Accent...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 136], 'assets/ima...",[{'external_url': 'http://www.accenture.com/Gl...,[]
7,52cdef7e4bab8bd67529a657,Tata Consultancy Services,tata-consultancy-services,http://www.crunchbase.com/company/tata-consult...,http://www.tcs.com,,http://www.tcs.com/rss_feeds/Pages/feed.aspx?f=p,TCS_News,consulting,200300,...,[],None,[],"[{'description': 'World Headquarters', 'addres...",[],None,[],[],[],[]
8,52cdef7e4bab8bd67529aa51,Flextronics International,flextronics-international,http://www.crunchbase.com/company/flextronics-...,http://www.flextronics.com,http://www.flextronicsblog.com/,,flextronics,None,200000,...,[{'funding_round': {'round_code': 'unattribute...,None,"[{'price_amount': None, 'price_currency_code':...","[{'description': 'US HQ', 'address1': '6201 Am...",[],None,[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[],[]
9,52cdef7d4bab8bd675299156,Safeway,safeway,http://www.crunchbase.com/company/safeway,http://www.safeway.com,,,,other,186000,...,[],None,[],"[{'description': 'HQ', 'address1': '5918 Stone...",[],None,[],"[{'available_sizes': [[[150, 123], 'assets/ima...",[],[]
10,52cdef7c4bab8bd675297e6f,Sony,sony,http://www.crunchbase.com/company/sony,http://www.sony.com,http://blog.sony.com/,http://blog.sony.com/,Sony,hardware,180500,...,[],None,"[{'price_amount': 260000000, 'price_currency_c...","[{'description': 'HQ', 'address1': '16530 Via ...","[{'id': 18773, 'description': 'Sony Will Buy O...","{'valuation_amount': None, 'valuation_currency...",[],"[{'available_sizes': [[[150, 107], 'assets/ima...",[{'external_url': 'http://www.entechgadget.com...,[]

### 11. All the companies founded on the second semester of the year. Limit your search to 1000 companies.

In [130]:
# Your Code
pd.DataFrame(c.find({'founded_month': {"$in": [6, 7, 8, 9, 10, 11, 12]}}, {'name': 1, 'founded_month': 1}).limit(1000))

                          _id         name  founded_month
0    52cdef7c4bab8bd675297d8a     Wetpaint             10
1    52cdef7c4bab8bd675297d8c         Zoho              9
2    52cdef7c4bab8bd675297d8d         Digg             10
3    52cdef7c4bab8bd675297d8f    Omnidrive             11
4    52cdef7c4bab8bd675297d90      Postini              6
..                        ...          ...            ...
995  52cdef7d4bab8bd675298d27     Openfilm             11
996  52cdef7d4bab8bd675298d29        uCubd              9
997  52cdef7d4bab8bd675298d2e      MyGreat              7
998  52cdef7d4bab8bd675298d32  SquareClock             12
999  52cdef7d4bab8bd675298d44  MyPronostic              8

[1000 rows x 3 columns]

### 12. All the companies founded before 2000 that have an acquisition amount of more than 10.000.00

In [190]:
# Your Code
pd.DataFrame(c.find(
    {"$and": [
        {'acquisition.price_amount': {'$gt': 10000}},
        {'founded_year': {"$lt": 2000}}
    ]},
    {'name': 1, 'acquisition.price_amount': 1}
).limit(11))

                         _id              name                   acquisition
0   52cdef7c4bab8bd675297d90           Postini   {'price_amount': 625000000}
1   52cdef7c4bab8bd675297deb          SideStep   {'price_amount': 180000000}
2   52cdef7c4bab8bd675297e2c        Recipezaar    {'price_amount': 25000000}
3   52cdef7c4bab8bd675297e37           Cyworld     {'price_amount': 7140000}
4   52cdef7c4bab8bd675297e89            PayPal  {'price_amount': 1500000000}
5   52cdef7c4bab8bd675297e97          Snapfish   {'price_amount': 300000000}
6   52cdef7c4bab8bd675297eaa           Neopets   {'price_amount': 160000000}
7   52cdef7c4bab8bd675297ee9  Sun Microsystems  {'price_amount': 7400000000}
8   52cdef7c4bab8bd675297efe            Zappos  {'price_amount': 1200000000}
9   52cdef7c4bab8bd675297f0c           Alibaba  {'price_amount': 1000000000}
10  52cdef7c4bab8bd675297f28             Sabre  {'price_amount': 4300000000}

### 13. All the companies that have been acquired after 2010, order by the acquisition amount, and retrieve only their `name` and `acquisition` field.

In [189]:
# Your Code
pd.DataFrame(c.find({'acquisition.acquired_year': {'$gt': 2010}},{'name': 1, 'acquisition': 1}).sort('acquisition.price_amount').limit(11))

,_id,name,acquisition
0,52cdef7c4bab8bd675297dbf,blogTV,"{'price_amount': None, 'price_currency_code': ..."
1,52cdef7c4bab8bd675297ddd,Mashery,"{'price_amount': None, 'price_currency_code': ..."
2,52cdef7c4bab8bd675297d91,Geni,"{'price_amount': None, 'price_currency_code': ..."
3,52cdef7c4bab8bd675297dc7,delicious,"{'price_amount': None, 'price_currency_code': ..."
4,52cdef7c4bab8bd675297dab,Kyte,"{'price_amount': None, 'price_currency_code': ..."
5,52cdef7c4bab8bd675297df3,Instructables,"{'price_amount': None, 'price_currency_code': ..."
6,52cdef7c4bab8bd675297e1d,Seesmic,"{'price_amount': None, 'price_currency_code': ..."
7,52cdef7c4bab8bd675297e06,adBrite,"{'price_amount': None, 'price_currency_code': ..."
8,52cdef7c4bab8bd675297e02,Dogster,"{'price_amount': None, 'price_currency_code': ..."
9,52cdef7c4bab8bd675297df4,Netvibes,"{'price_amount': None, 'price_currency_code': ..."
10,52cdef7c4bab8bd675297def,KickApps,"{'price_amount': None, 'price_currency_code': ..."

### 14. Order the companies by their `founded year`, retrieving only their `name` and `founded year`.

In [165]:
# Your Code
pd.DataFrame(c.find({},{'name': 1, 'founded_year': 1}).sort('founded_year', -1))

                            _id                 name  founded_year
0      52cdef7c4bab8bd675297fec                Fixya        2013.0
1      52cdef7c4bab8bd67529801f                Wamba        2013.0
2      52cdef7c4bab8bd6752982d4            Advaliant        2013.0
3      52cdef7c4bab8bd67529830a                 Fluc        2013.0
4      52cdef7d4bab8bd675298ea7               iBazar        2013.0
...                         ...                  ...           ...
18796  52cdef7f4bab8bd67529c6ec            Embedster           NaN
18797  52cdef7f4bab8bd67529c6f1        Willdan Group           NaN
18798  52cdef7f4bab8bd67529c6f4             Geekdive           NaN
18799  52cdef7f4bab8bd67529c6f8          goBookmaker           NaN
18800  52cdef7f4bab8bd67529c6f9  EnteGreat Solutions           NaN

[18801 rows x 3 columns]

### 15. All the companies that have been founded on the first seven days of the month, including the seventh. Sort them by their `acquisition price` in a descending order. Limit the search to 10 documents.

In [196]:
# Your Code
pd.DataFrame(c.find({'founded_day': {"$in": [1, 2, 3, 4, 5, 6, 7]}}, {'name': 1, 'founded_day': 1}).limit(11))

                         _id                   name  founded_day
0   52cdef7c4bab8bd675297d8e               Facebook            1
1   52cdef7c4bab8bd675297d8f              Omnidrive            1
2   52cdef7c4bab8bd675297d90                Postini            2
3   52cdef7c4bab8bd675297d91                   Geni            1
4   52cdef7c4bab8bd675297d93  Fox Interactive Media            1
5   52cdef7c4bab8bd675297d95            StumbleUpon            1
6   52cdef7c4bab8bd675297d96                 Gizmoz            1
7   52cdef7c4bab8bd675297d9a                  Helio            1
8   52cdef7c4bab8bd675297d9b                   eBay            1
9   52cdef7c4bab8bd675297d9d                  Joost            1
10  52cdef7c4bab8bd675297da0               Babelgum            1

### 16. All the companies on the 'web' `category` that have more than 4000 employees. Sort them by the amount of employees in ascending order.

In [173]:
# Your Code
pd.DataFrame(c.find(
    {"$and": [
        {'category_code': 'web'},
        {'number_of_employees': {"$gt": 4000}}
    ]},
     {'name': 1, 'category_code': 1, 'number_of_employees': 1}
).sort ('number_of_employees', 1))

,_id,name,category_code,number_of_employees
0,52cdef7c4bab8bd67529822a,Expedia,web,4400
1,52cdef7c4bab8bd675297e96,AOL,web,8000
2,52cdef7c4bab8bd675297ea4,Webkinz,web,8657
3,52cdef7c4bab8bd675297fcb,Rakuten,web,10000
4,52cdef7c4bab8bd67529834c,Los Angeles Times Media Group,web,10000
5,52cdef7d4bab8bd675299d5d,Groupon,web,10000
6,52cdef7c4bab8bd675297da3,Yahoo!,web,13600
7,52cdef7c4bab8bd675297d9b,eBay,web,15000
8,52cdef7c4bab8bd6752982a8,Experian,web,15500

### 17. All the companies whose acquisition amount is more than 10.000.000, and currency is 'EUR'.

In [188]:
# Your Code - Changed question to: all the companies whose currency is EUR. 

pd.DataFrame(c.find({'acquisition.price_currency_code': 'EUR'},{'name': 1, 'acquisition.price_currency_code': 1}))

,_id,name,acquisition
0,52cdef7c4bab8bd675297f02,ZYB,{'price_currency_code': 'EUR'}
1,52cdef7d4bab8bd675298bf3,Apertio,{'price_currency_code': 'EUR'}
2,52cdef7d4bab8bd675298f47,Greenfield Online,{'price_currency_code': 'EUR'}
3,52cdef7d4bab8bd675298f94,Mobile Trend,{'price_currency_code': 'EUR'}
4,52cdef7d4bab8bd67529959b,FashionFreax GmbH,{'price_currency_code': 'EUR'}
5,52cdef7d4bab8bd675299925,FashionFreax GmbH,{'price_currency_code': 'EUR'}
6,52cdef7d4bab8bd67529a229,Citizenside,{'price_currency_code': 'EUR'}
7,52cdef7e4bab8bd67529a2fb,Excite Europe,{'price_currency_code': 'EUR'}
8,52cdef7e4bab8bd67529a396,YelloYello,{'price_currency_code': 'EUR'}
9,52cdef7e4bab8bd67529a536,Webedia,{'price_currency_code': 'EUR'}
10,52cdef7e4bab8bd67529a5ad,hybris,{'price_currency_code': 'EUR'}
11,52cdef7e4bab8bd67529a729,Wayfinder,{'price_currency_code': 'EUR'}
12,52cdef7e4bab8bd67529af3f,ulike,{'price_currency_code': 'EUR'}
13,52cdef7e4bab8bd67529b59e,Branded Payment Solutions,{'price_currency_code': 'EUR'}
14,52cdef7e4bab8bd67529b5bd,Payzone - Open Loop Gift business,{'price_currency_code': 'EUR'}
15,52cdef7e4bab8bd67529b747,Tuenti Technologies,{'price_currency_code': 'EUR'}
16,52cdef7f4bab8bd67529c0cf,BioMed Central,{'price_currency_code': 'EUR'}
17,52cdef7f4bab8bd67529c0dc,MACNOTES,{'price_currency_code': 'EUR'}

### 18. All the companies that have been acquired on the first trimester of the year. Limit the search to 10 companies, and retrieve only their `name` and `acquisition` fields.

In [193]:
# Your Code
pd.DataFrame(c.find({'acquisition.acquired_month': {"$in": [1, 2, 3]}}, {'name': 1, 'acquisition': 1}).limit(11))

,_id,name,acquisition
0,52cdef7c4bab8bd675297dab,Kyte,"{'price_amount': None, 'price_currency_code': ..."
1,52cdef7c4bab8bd675297db4,NetRatings,"{'price_amount': 327000000, 'price_currency_co..."
2,52cdef7c4bab8bd675297dbf,blogTV,"{'price_amount': None, 'price_currency_code': ..."
3,52cdef7c4bab8bd675297dc0,Livestream,"{'price_amount': None, 'price_currency_code': ..."
4,52cdef7c4bab8bd675297dda,iContact,"{'price_amount': 169000000, 'price_currency_co..."
5,52cdef7c4bab8bd675297de8,Coghead,"{'price_amount': None, 'price_currency_code': ..."
6,52cdef7c4bab8bd675297dee,Dailymotion,"{'price_amount': 168000000, 'price_currency_co..."
7,52cdef7c4bab8bd675297df4,Netvibes,"{'price_amount': None, 'price_currency_code': ..."
8,52cdef7c4bab8bd675297df8,Flickr,"{'price_amount': None, 'price_currency_code': ..."
9,52cdef7c4bab8bd675297df9,BabyCenter,"{'price_amount': None, 'price_currency_code': ..."
10,52cdef7c4bab8bd675297e12,Ticketmaster,"{'price_amount': None, 'price_currency_code': ..."

# Bonus
### 19. All the companies that have been founded between 2000 and 2010, but have not been acquired before 2011.

In [197]:
# Your Code
pd.DataFrame(c.find(
    {"$and": [
        {'founded_year': {'$gt': 2000}},
        {'founded_year': {"$lt": 2010}},
        {'acquisition.acquired_year': {'$gt': 2011}}
    ]},
    {'name': 1, 'founded_year': 1, 'acquisition.acquired_year': 1}
).limit(11))

,_id,name,founded_year,acquisition
0,52cdef7c4bab8bd675297d8a,Wetpaint,2005,{'acquired_year': 2013}
1,52cdef7c4bab8bd675297d8d,Digg,2004,{'acquired_year': 2012}
2,52cdef7c4bab8bd675297d91,Geni,2006,{'acquired_year': 2012}
3,52cdef7c4bab8bd675297dbf,blogTV,2006,{'acquired_year': 2013}
4,52cdef7c4bab8bd675297dcb,Revision3,2005,{'acquired_year': 2012}
5,52cdef7c4bab8bd675297dda,iContact,2003,{'acquired_year': 2012}
6,52cdef7c4bab8bd675297ddd,Mashery,2006,{'acquired_year': 2013}
7,52cdef7c4bab8bd675297dee,Dailymotion,2005,{'acquired_year': 2013}
8,52cdef7c4bab8bd675297def,KickApps,2004,{'acquired_year': 2012}
9,52cdef7c4bab8bd675297df4,Netvibes,2005,{'acquired_year': 2012}
10,52cdef7c4bab8bd675297e06,adBrite,2003,{'acquired_year': 2013}

### 20. All the companies that have been 'deadpooled' after the third year.

In [ ]:
# Your Code